services:
  # Frontend Service
  - type: web
    name: newsofvideos-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: no-referrer-when-downgrade
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
